class ItemList{
   static List<String>food=[
     "15-minute chicken & halloumi burgers",
     "Apple Frangipan Tart",
     "Apple & Blackberry Crumble",
     "Apam balik",
     "Ayam Percik",
     "Bakewell tart",
     "Bread and Butter Pudding",
     "Baingan Bharta",
     "Beef Brisket Pot Roast",
     "Beef Sunday Roast",
     "Braised Beef Chilli",
     "Beef stroganoff",
     "Broccoli & Stilton soup",
     "Bean & Sausage Hotpot",
     "Banana Pancakes",
     "Beef Dumpling Stew",
     "Beef and Mustard Pie",
     "Beef and Oyster pie",
     "Blackberry Fool",
     "Battenberg Cake",
     "Beef Bourguignon",
     "Brie wrapped in prosciutto & brioche",
     "Boulangère Potatoes",
     "BeaverTails",
     "Brown Stew Chicken",
     "Baked salmon with fennel & tomatoes",
     "Budino Di Ricotta",
     "Breakfast Potatoes",
     "BBQ Pork Sloppy Joes",
     "Big Mac",
     "Bigos",
     "Boxty Breakfast",
     "Beef Rendang",
     "Burek",
     "Bistek",
     "Bread omelette",
     "Beetroot Soup",
     "Blini Pancakes",
     "Chocolate Gateau",
     "Chicken Enchilada Casserole",
     "Cream Cheese Tart",
     "Christmas Pudding Flapjack",
     "Chicken Handi",
     "Chick-Fil-A Sandwich",
     "Chicken Alfredo Primavera",
     "Chicken Fajita Mac and Cheese",
     "Cajun spiced fish tacos",
     "Crock Pot Chicken Baked Tacos",
     "Chicken Karaage",
     "Coq au vin",
     "Chilli prawn linguine",
     "Clam chowder",
     "Creamy Tomato Soup",
     "Chicken & mushroom Hotpot",
     "Chicken Couscous",
     "Chocolate Avocado Mousse",
     "Choc Chip Pecan Pie",
     "Chocolate Raspberry Brownies",
     "Chickpea Fajitas",
     "Chicken Ham and Leek Pie",
     "Chicken Parmentier",
     "Carrot Cake",
     "Chelsea Buns",
     "Chocolate Souffle",
     "Chinon Apple Tarts",
     "Chicken Marengo",
     "Canadian Butter Tarts",
     "Chicken Basquaise",
     "Callaloo Jamaican Style",
     "Chicken Congee",
     "Chocolate Caramel Crispy",
     "Chakchouka",
     "Cashew Ghoriba Biscuits",
     "Corba",
     "Christmas Pudding Trifle",
     "Classic Christmas pudding",
     "Christmas cake",
     "Corned Beef and Cabbage",
     "Crispy Sausages and Greens",
     "Chicken Quinoa Greek Salad",
     "Chick-Fil-A Sandwich",
     "Coddled pork with cider",
     "Cevapi Sausages",
     "Croatian lamb peka",
     "Croatian Bean Stew",
     "Chivito uruguayo",
     "Crispy Eggplant",
     "Cabbage Soup",
     "Dal fry",
     "Dundee cake",
     "Duck Confit",
     "Eton Mess",
     "Eccles Cakes",
     "English Breakfast",
     "Escovitch Fish",
     "Egg Drop Soup",
     "Eggplant Adobo",
     "Egyptian Fatteh",
     "Feteer Meshaltet",
     "Fish pie",
     "French Lentils With Garlic and Thyme",
     "Fettucine alfredo",
     "Full English Breakfast",
     "French Onion Soup",
     "Flamiche",
     "French Omelette",
     "Fish Stew with Rouille",
     "Fennel Dauphinoise",
     "Fruit and Cream Cheese Breakfast Pastries",
     "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
     "Ful Medames",
     "Feteer Meshaltet",
     "Fettuccine Alfredo",
     "Fish Soup",
     "Garides Saganaki",
     "Grilled Mac and Cheese Sandwich",
     "General Tso's Chicken",
     "Gigantes Plaki",
     "Gołąbki",
     "Grilled Portuguese sardines",
     "Grilled eggplant with coconut milk",
     "Honey Teriyaki Salmon",
     "Hot Chocolate Fudge",
     "Hot and Sour Soup",
     "Home-made Mandazi",
     "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
     "Honey Yogurt Cheesecake",
     "Ham hock colcannon",
     "Irish stew",
     "Jam Roly-Poly",
     "Jerk chicken with rice & peas",
     "Jamaican Beef Patties",
     "Japanese gohan rice",
     "Japanese Katsudon",
     "Kapsalon",
     "Kentucky Fried Chicken",
     "Katsu Chicken curry",
     "Key Lime Pie",
     "Kidney Bean Curry",
     "Kedgeree",
     "Kung Pao Chicken",
     "Kung Po Prawns",
     "Kafteji",
     "Keleya Zaara",
     "Kumpir",
     "Krispy Kreme Donut",
     "Koshari",
     "Lamb tomato and sweet spices",
     "Lamb Biryani",
     "Lamb Rogan josh",
     "Laksa King Prawn Noodles",
     "Lamb Tagine",
     "Lasagne",
     "Lamb and Potato pie",
     "Lancashire hotpot",
     "Leblebi Soup",
     "Lasagna Sandwiches",
     "Lamb and Lemon Souvlaki",
     "Lamb Tzatziki Burgers",
     "Lamb Pilaf",
     "Mediterranean Pasta Salad",
     "Massaman Beef curry",
     "Mushroom & Chestnut Rotolo",
     "Matar Paneer",
     "Minced Beef Pie",
     "McSinghs Scotch pie",
     "Madeira Cake",
     "Montreal Smoked Meat",
     "Ma Po Tofu",
     "Mince Pies",
     "Moussaka",
     "Mulukhiyah",
     "Mustard champ",
     "Moroccan Carrot Soup",
     "Mee goreng mamak",
     "Mushroom soup with buckwheat",
     "Nutty Chicken Curry",
     "New York cheesecake",
     "Nanaimo Bars",
     "Nasi lemak",
     "Oxtail with broad beans",
     "Osso Buco alla Milanese",
     "Pad See Ew",
     "Potato Gratin with Chicken",
     "Poutine",
     "Pilchard puttanesca",
     "Pork Cassoulet",
     "Pancakes",
     "Pumpkin Pie",
     "Peanut Butter Cheesecake",
     "Peach & Blueberry Grunt",
     "Parkin Cake",
     "Pear Tarte Tatin",
     "Provençal Omelette Cake",
     "Prawn & Fennel Bisque",
     "Pate Chinois",
     "Pouding chomeur",
     "Peanut Butter Cookies",
     "Pizza Express Margherita",
     "Paszteciki",
     "Pierogi",
     "Polskie Naleśniki",
     "Piri-piri chicken and slaw",
     "Portuguese prego with green piri-piri",
     "Portuguese barbecued pork",
     "Portuguese fish stew",
     "Portuguese custard tarts",
     "Potato Salad",
     "Rigatoni with fennel sausage sauce",
     "Rocky Road Fudge",
     "Ribollita",
     "Roasted Eggplant With Tahini, Pine Nuts, and Lentils",
     "Rock Cakes",
     "Ratatouille",
     "Rappie Pie",
     "Red Peas Soup",
     "Roast fennel and aubergine paella",
     "Rosół",
     "Rogaliki",
     "Roti john",
     "Spanish Tortilla",
     "Steak and Kidney Pie",
     "Sticky Toffee Pudding",
     "Spotted Dick",
     "Summer Pudding",
     "Summer Pistou",
     "Split Pea Soup",
     "Sugar Pie",
     "Steak Diane",
     "Saltfish and Ackee",
     "Sweet and Sour Pork",
     "Szechuan Beef",
     "Shrimp Chow Fun",
     "Salmon Avocado Salad",
     "Salmon Eggs Eggs Benedict",
     "Shakshuka",
     "Smoked Haddock Kedgeree",
     "Stamppot",
     "Snert",
     "Spaghetti alla Carbonara",
     "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
     "Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini",
     "Strawberry Rhubarb Pie",
     "Stuffed Lamb Tomatoes",
     "Sledz w Oleju",
     "Shawarma",
     "Spring onion and prawn empanadas",
     "Seri muka kuih",
     "Sushi",
     "Stuffed Bell Peppers with Quinoa and Black Beans",
     "Strawberries Romanoff",
     "Spaghetti Bolognese",
     "Spicy Arrabiata Penne",
     "Smoky Lentil Chili with Squash",
     "Sticky Toffee Pudding Ultimate",
     "Spicy North African Potato Salad",
     "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
     "Salmon Prawn Risotto",
     "Salted Caramel Cheescake",
     "Seafood fideuà",
     "Spinach & Ricotta Cannelloni",
     "Squash linguine",
     "Thai Green Curry",
     "Toad In The Hole",
     "Turkey Meatloaf",
     "Tuna Nicoise",
     "Tahini Lentils",
     "Three Fish Pie",
     "Treacle Tart",
     "Tarte Tatin",
     "Three-cheese souffles",
     "Tourtiere",
     "Timbits",
     "Tunisian Orange Cake",
     "Tunisian Lamb Soup",
     "Tuna and Egg Briks",
     "Tamiya",
     "Tonkatsu pork",
     "Traditional Croatian Goulash",
     "Tortang Talong",
     "Vegetarian Casserole",
     "Vegetarian Chilli",
     "Vegetable Shepherd's Pie",
     "Vegan Lasagna",
     "Vegan Chocolate Cake",
     "Vietnamese Grilled Pork",
     "Venetian Duck Ragu",
     "Walnut Roll Gužvara",
     "Wontons",
     "White chocolate creme brulee",
     "Yaki Udon",
   ];
   String menu;
   ItemList({required this.menu});
   static fetching (String list) async {
     if(list=="Indian"){
       return ItemList.Indian;
     }
     else if(list=="Egyptian"){
       return ItemList.Egyptian;
     }
     else if(list=="Japanese"){
       return ItemList.Japanese;
     }
     else if(list=="American"){
       return ItemList.American;
     }
     else if(list=="Canadian"){
       return ItemList.Canadian;
     }
     else if(list=="Tunisian"){
       return ItemList.Tunisian;
     }
     else if(list=="Chinese"){
       return ItemList.Chinese;
     }
   }
   static List<String>foodImages=[
     "https://st2.depositphotos.com/1177973/8430/i/450/depositphotos_84309564-stock-photo-still-life-with-various-types.jpg",
     "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
     "https://burst.shopifycdn.com/photos/flatlay-iron-skillet-with-meat-and-other-food.jpg?width=1000&format=pjpg&exif=0&iptc=0",
     "https://w0.peakpx.com/wallpaper/467/393/HD-wallpaper-food-dessert-still-life.jpg",
     "https://static.vecteezy.com/system/resources/thumbnails/026/721/935/small_2x/indian-national-food-close-up-generative-ai-photo.jpg",
     "https://media.istockphoto.com/id/1316145932/photo/table-top-view-of-spicy-food.jpg?b=1&s=612x612&w=0&k=20&c=X6CkFGpSKhNZeiii8Pp2M_YrBdqs7tRaBytkGi48a0U="
   ];
   static List<String>American=[
     "53085",
     "52855",
     "52995",
     "52812",
     "53013",
     "53016",
     "52818",
     "52856",
     "52860",
     "52840",
     "52996",
     "52957",
     "52829",
     "52993",
     "52787",
     "52813",
     "52859",
     "53015",
     "52987",
     "52858",
     "52854",
     "52862",
     "52861",
     "52958",
     "52857",
     "52816",
     "52786",
     "52962",
     "52833",
     "52994",
     "52992",
     "52817",
     "52794"
   ];
   static List<String>Indian=[
     "52807",
     "53076",
     "52795",
     "52785",
     "52868",
     "52805",
     "52808",
     "52865",
     "52851",
     "52809",
     "52964",
     "52806"
   ];
   static List<String>Chinese=[
     "52952",
     "52956",
     "52955",
     "52951",
     "52954",
     "52946",
     "52947",
     "52953",
     "52949",
     "52950",
     "52948"
   ];
   static List<String>Canadian=[
     "52923",
     "52927",
     "52924",
     "52930",
     "52932",
     "52804",
     "52933",
     "52925",
     "52931",
     "52929",
     "52926"
   ];
   static List<String>Japanese=[
     "52831",
     "52773",
     "53033",
     "53034",
     "52820",
     "53065",
     "52772",
     "53032",
     "52871"
   ];
   static List<String>Tunisian=[
     "52976",
     "52969",
     "52971",
     "52974",
     "52973",
     "52975",
     "52972",
     "52970"
   ];
   static List<String>Egyptian=[
     "53031",
     "53030",
     "53025",
     "53027",
     "53029",
     "52963",
     "53028",
     "53026"
   ];
}